### ISSUE TITLE
Fix Test Failures

### ISSUE THREAD

**Issue by waynew** [saltstack/salt-ext-modules-vmware#178]
These tests failed for me when running the full test suite (i.e. `python -m tests-3`) with a fresh vcenter.conf and vmc.conf for testing:

- [ ] [`tests.integration.modules.test_datacenter : test_get`](https://github.com/saltstack/salt-ext-modules-vmware/issues/150)
- [ ] [`tests.integration.modules.test_esxi : test_esxi_get_lun_ids_should_return_lun_NAA_ids`](https://github.com/saltstack/salt-ext-modules-vmware/issues/151)
- [ ] [`tests.integration.modules.test_esxi : test_manage_service`](https://github.com/saltstack/salt-ext-modules-vmware/issues/152)
- [ ] [`tests.integration.modules.test_esxi : test_acceptance_level`](https://github.com/saltstack/salt-ext-modules-vmware/issues/153)
- [ ] [`tests.integration.modules.test_esxi : test_advanced_config`](https://github.com/saltstack/salt-ext-modules-vmware/issues/154)
- [ ] [`tests.integration.modules.test_esxi : test_get_dns_config`](https://github.com/saltstack/salt-ext-modules-vmware/issues/155)
- [ ] [`tests.integration.modules.test_esxi : test_get_firewall_config`](https://github.com/saltstack/salt-ext-modules-vmware/issues/156)
- [ ] [`tests.integration.modules.test_esxi : test_add`](https://github.com/saltstack/salt-ext-modules-vmware/issues/157)
- [ ] [`tests.integration.modules.test_esxi : test_manage_disconnect`](https://github.com/saltstack/salt-ext-modules-vmware/issues/158)
- [ ] [`tests.integration.modules.test_esxi : test_move`](https://github.com/saltstack/salt-ext-modules-vmware/issues/159)
- [ ] [`tests.integration.modules.test_esxi : test_manage_connect`](https://github.com/saltstack/salt-ext-modules-vmware/issues/160)
- [ ] [`tests.integration.modules.test_esxi : test_manage_remove`](https://github.com/saltstack/salt-ext-modules-vmware/issues/161)
- [ ] [`tests.integration.modules.test_esxi : test_esxi_get`](https://github.com/saltstack/salt-ext-modules-vmware/issues/162)
- [ ] [`tests.integration.modules.test_nsxt_compute_manager : test_register_update_and_remove`](https://github.com/saltstack/salt-ext-modules-vmware/issues/163)
- [ ] [`tests.integration.modules.test_nsxt_ip_blocks : test_nsxt_ip_blocks_execution_module_crud_operations`](https://github.com/saltstack/salt-ext-modules-vmware/issues/164)
- [ ] [`tests.integration.modules.test_nsxt_ip_pools : test_nsxt_ip_pools_execution_module_crud_operations`](https://github.com/saltstack/salt-ext-modules-vmware/issues/165)
- [ ] [`tests.integration.modules.test_nsxt_license : test_apply_license`](https://github.com/saltstack/salt-ext-modules-vmware/issues/166)
- [ ] [`tests.integration.modules.test_nsxt_license : test_get_licenses`](https://github.com/saltstack/salt-ext-modules-vmware/issues/167)
- [ ] [`tests.integration.modules.test_nsxt_license : test_delete_license`
- [ ] [`tests.integration.modules.test_nsxt_manager : test_nsxt_manager_get_and_set_manager_config`](https://github.com/saltstack/salt-ext-modules-vmware/issues/168)
- [ ] [`tests.integration.modules.test_nsxt_transport_node : test_check_transport_nodes`](https://github.com/saltstack/salt-ext-modules-vmware/issues/169)
- [ ] [`tests.integration.modules.test_nsxt_transport_node_profiles : test_nsxt_transport_node_profiles_execution_module`](https://github.com/saltstack/salt-ext-modules-vmware/issues/170)
- [ ] [`tests.integration.modules.test_nsxt_transport_zone : test_check_transport_zone`](https://github.com/saltstack/salt-ext-modules-vmware/issues/171)
- [ ] `tests.integration.modules.test_nsxt_uplink_profiles : test_nsxt_uplink_profiles_execution_module`
- [ ] [`tests.integration.modules.test_vm : test_ovf_deploy`](https://github.com/saltstack/salt-ext-modules-vmware/issues/172)
- [ ] `tests.integration.modules.test_vm : test_ova_deploy` (same as ovf_deploy)
- [ ] [`tests.integration.states.test_datacenter : test_present`](https://github.com/saltstack/salt-ext-modules-vmware/issues/173)
- [ ] `tests.integration.states.test_datacenter : test_absent` - same as test_present
- [ ] `tests.integration.states.test_datacenter : test_present_dry_run` - same as test_present
- [ ] `tests.integration.states.test_datacenter : test_absent_dry_run` - same as test_present
- [ ] [`tests.integration.states.test_folder : test_move_folder`](https://github.com/saltstack/salt-ext-modules-vmware/issues/174)
- [ ] `tests.integration.states.test_nsxt_compute_manager : test_register_update_and_delete` - path-to-nsxt-cert.pem issue
- [ ] [`tests.integration.states.test_nsxt_ip_blocks : test_nsxt_ip_blocks_state_module`](https://github.com/saltstack/salt-ext-modules-vmware/issues/175)
- [ ] `tests.integration.states.test_nsxt_ip_pools : test_nsxt_ip_pools_present_and_absent_states`- same as above blocs_state_module
- [ ] [`tests.integration.states.test_nsxt_license : test_nsxt_licenses_state_module` - path-to-nsxt-cert.pem problem
- [ ] [`tests.integration.states.test_nsxt_manager : test_nsxt_manager` - same as above
- [ ] [`tests.integration.states.test_nsxt_transport_node : test_state_transport_node_verify`]() (probably same as above)
- [ ] `tests.integration.states.test_nsxt_transport_node_profiles : test_nsxt_transport_node_profiles_present_and_absent_states` 'error' not in error (probably cert problem)
- [ ] [`tests.integration.states.test_nsxt_transport_zone : test_state_transport_zone_verify`](https://github.com/saltstack/salt-ext-modules-vmware/issues/177)
- [ ] `tests.integration.states.test_nsxt_uplink_profiles : test_nsxt_uplink_profiles_present_and_absent_states` - error not in error, probably cert issue
